version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    container_name: nginx
    volumes:
      - data:/var/www/html
    networks:
      - nat
    restart: always
    env_file:
      - .env
    image: nginx:inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - data:/var/www/html
    networks:
      - nat
    restart: always
    env_file:
      - .env
    image: wordpress:inception
    depends_on:
      - mariadb
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    networks:
      - nat
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    image: mariadb:inception

volumes:
  data:
  mariadb_data:
networks:
  nat:
    driver: bridge