version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    container_name: nginx
    volumes:
      - data:/var/www/html
    networks:
      - nat
    restart: always
    env_file:
      - .env
    image: nginx:inception
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - data:/var/www/html
    networks:
      - nat
    restart: always
    env_file:
      - .env
    image: wordpress:inception
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - nat
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    image: mariadb:inception

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/selhilal/data/wordpress'
      o: 'bind'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/selhilal/data/mariadb'
      o: 'bind'
networks:
  nat:
    driver: bridge